# Language edits for the MSJ version (author's copy-edit, screened against academic-paper/references/academic_writing_style.md):
# literature findings and completed procedures in past tense, consistent article use ("the HOSE"), US date format,
# commas after introductory phrases, numbers below ten in words. Edits that changed meaning were not applied
# (listed in paper2/process/language_edit_log.md).
EDITS = [
 # --- 1. Introduction ---
 ("A daily price limit prevents a stock from moving beyond a fixed band within one trading day.",
  "A daily price limit prevents stocks from moving beyond a fixed band within a single trading day."),
 ("postpones their adjustments.", "postpones adjustment."),
 ("Studies on band changes document the effects", "Studies on band changes have documented the effects"),
 ("and account-level data show that large investors", "and account-level data have shown that large investors"),
 ("and the records we could access have no magnitudes.", "and the records we could access had no magnitudes."),
 ("that controls for the other price-based signals", "that controls for other price-based signals"),
 ("split it into overnight gap and intraday return,", "split it into an overnight gap and an intraday return,"),
 ("We make three contributions.", "This study makes three contributions."),
 # --- 1.1 literature: findings in past tense ---
 ("Models predict protection or distortion, depending on the source", "Models predict protection or distortion depending on the source"),
 ("Brennan (1986) rationalizes", "Brennan (1986) rationalized"),
 ("Kodres and O'Brien (1994) show that", "Kodres and O'Brien (1994) showed that"),
 ("Greenwald and Stein (1991) link crashes", "Greenwald and Stein (1991) linked crashes"),
 ("Subrahmanyam (1994) shows that halts can advance trades in time and raise price variability, and in the model of Chen et al. (2024), volatility",
  "Subrahmanyam (1994) showed that halts can advance trades in time and raise price variability. In the model of Chen et al. (2024), volatility"),
 ("Kim and Rhee (1997) find support", "Kim and Rhee (1997) found support"),
 ("Bildik and Gülay (2006) find the same in Istanbul", "Bildik and Gülay (2006) found the same result in Istanbul"),
 ("Chen (1993) finds that serial correlation falls", "Chen (1993) found that serial correlation decreases"),
 ("Berkman and Lee (2002) examine volatility and trading activity around a revision", "Berkman and Lee (2002) examined volatility and trading activity around the revision"),
 ("Huang et al. (2001) report for Taiwan that the overnight overreaction after limit hits reverses during the following day",
  "Huang et al. (2001) reported for Taiwan that the overnight overreaction after limit hits reverses the following day"),
 ("Cho et al. (2003) find a magnet effect", "Cho et al. (2003) found a magnet effect"),
 ("Kim and Limpaphayom (2000) show that small, volatile, high-volume stocks", "Kim and Limpaphayom (2000) showed that small, volatile, and high-volume stocks"),
 ("Deb et al. (2013) argue that", "Deb et al. (2013) argued that"),
 ("Qi (2023) confirms delayed price discovery, volatility spillover, and trading interference, stronger at the lower limit and with no magnet effect; Zhang et al. (2022) find higher liquidity, volatility, and probability of informed trading; and Jia et al. (2024) find lower crash risk.",
  "Qi (2023) confirmed delayed price discovery, volatility spillover, and trading interference, stronger at the lower limit and with no magnet effect. Zhang et al. (2022) found higher liquidity, volatility, and probability of informed trading, and Jia et al. (2024) found lower crash risk."),
 ("net buying predicts stronger long-run reversal", "net buying predicts a stronger long-run reversal"),
 ("Stocks with large limit exposure attract attention and earn lower future returns, most where", "Stocks with large limit exposures attract attention and earn lower future returns, especially where"),
 ("Kelly and Clark (2011) show for index funds that overnight and intraday returns differ.", "Kelly and Clark (2011) showed that overnight and intraday returns differ for index funds."),
 ("Aboody et al. (2018) tie overnight", "Aboody et al. (2018) tied overnight"),
 ("Lou et al. (2019) find overnight", "Lou et al. (2019) found overnight"),
 ("Akbas et al. (2022) find that persistent positive-overnight, negative-daytime patterns", "Akbas et al. (2022) found that persistent positive-overnight and negative-daytime patterns"),
 ("Bogousslavsky (2021) links the split", "Bogousslavsky (2021) linked the split"),
 ("and Lu et al. (2023) link it to", "and Lu et al. (2023) linked it to"),
 ("which Qiao and Dam (2020) link to", "which Qiao and Dam (2020) linked to"),
 ("Harvey et al. (2016) argue that a new factor", "Harvey et al. (2016) argued that a new factor"),
 ("Harvey and Liu (2020) tie the hurdle", "Harvey and Liu (2020) tied the hurdle"),
 ("Hou et al. (2020) find that, with microcaps mitigated,", "Hou et al. (2020) found that with microcaps mitigated,"),
 ("Petersen (2009) compares standard-error estimators", "Petersen (2009) compared standard-error estimators"),
 ("Gutierrez and Kelley (2008) study weekly returns", "Gutierrez and Kelley (2008) studied weekly returns"),
 ("Huang et al. (2023) find a size effect", "Huang et al. (2023) found a size effect"),
 ("post-limit returns on HOSE.", "post-limit returns on the HOSE."),
 ("These studies compare band regimes, sort stocks by limit exposure, or split", "These studies compared band regimes, sorted stocks by limit exposure, or split"),
 ("only Huang et al. (2001) link limit hits", "only Huang et al. (2001) linked limit hits"),
 ("and none controls for multiple testing or uses the 2025", "and none controlled for multiple testing or used the 2025"),
 ("a ceiling close predicts a positive next-day abnormal return and a floor close a negative one", "a ceiling close predicts a positive next-day abnormal return, and a floor close predicts a negative one"),
 ("absorbs the blocked demand", "absorbs blocked demand"),
 ("after moves of similar size", "after moves of a similar size"),
 ("earns no positive abnormal return through", "earns no positive abnormal returns through"),
 # --- 2. Materials and Methods ---
 ("On 24 September 2026, we downloaded", "On September 24, 2026, we downloaded"),
 ("rows, all instrument types)", "rows for all instrument types)"),
 ("with records through 23 September 2026, and we use the", "with records through September 23, 2026, and we used the"),
 ("trading days from 21 August 2024.", "trading days from August 21, 2024."),
 ("*Sample.* We keep the", "*Sample.* We kept the"),
 ("*Institutional setting.* HOSE sets", "*Institutional setting.* The HOSE sets"),
 ("On 5 May 2025, HOSE moved", "On May 5, 2025, the HOSE moved"),
 ("The band stayed unchanged", "The band remained unchanged"),
 ("$C_{i,d} = H_{i,d}$, and a floor event has", "$C_{i,d} = H_{i,d}$, whereas a floor event has"),
 ("from day 61, once a 60-day", "from day 61, when a 60-day"),
 ("(see Section 4.1 on vendor price adjustment)", "(see Section 4.1, vendor price adjustment)"),
 ("stocks weighted with $w_{j,d}$", "stocks weighted by $w_{j,d}$"),
 ("because each outcome needs different data", "because each outcome requires different data"),
 ("require the open and close of day *d*+1", "require the opening and closing prices of day *d*+1"),
 ("also requires the day-*d*+5 close,", "also requires the day-*d*+5 closing price,"),
 ("No event is dropped for any other reason.", "No event was dropped for any other reason."),
 ("and take a normal reference; Table 1 *t*-statistics", "and take a normal reference. Table 1 *t*-statistics"),
 ("Each week we rank-normalize", "Each week, we rank-normalize"),
 ("with weekly intercept $a_\\tau$", "with a weekly intercept $a_\\tau$"),
 ("uses Newey and West (1987) standard errors (four lags, Bartlett weights, no prewhitening)", "uses Newey and West's (1987) standard errors (four lags, Bartlett weights, and no prewhitening)"),
 ("between the extreme quintiles, before and after", "between the extreme quintiles before and after"),
 ("and we also report Holm (1979) adjustments", "We also report Holm's (1979) adjustments"),
 ("(the first 39 weeks, or events up to", "(the first 39 weeks or events up to"),
 ("Lookbacks overlap the discovery half", "Lookbacks overlap with the discovery half"),
 ("every candidate signal in the plan; Section 3 reports", "every candidate signal in the plan. Section 3 reports"),
 ("before computing results.", "before computing the results."),
 ("no external registry holds it and we had", "no external registry holds it, and we had"),
 ("rest on them: the decomposition,", "rest on them: decomposition,"),
 ("so effect sizes may be overstated", "so the effect sizes may be overstated"),
 ("One script reproduces every number, table, and figure; code, data,", "One script reproduces every number, table, and figure; the code, data,"),
 # --- 3. Results ---
 ("The event sample holds", "The event sample contains"),
 ("standard deviation, so the null excludes only large effects. With eight Newey–West lags the largest",
  "standard deviation; therefore, the null excludes only large effects. With eight Newey–West lags, the largest"),
 ("find in Vietnam, so our null does not contradict theirs.", "found in Vietnam; therefore, our null result does not contradict theirs."),
 ("conclusion about market efficiency from it.", "conclusion about market efficiency."),
 ("Table 1 reports the event tests.", "Table 1 presents the results of the event tests."),
 ("keep their signs in both halves", "maintain their signs in both halves"),
 ("survive the rule re-applied", "survive the rule reapplied"),
 ("over days *d*+2 to *d*+5 the ceiling return", "over days *d*+2 to *d*+5, the ceiling return"),
 ("the ceiling test would fail and the floor test", "the ceiling test would fail, and the floor test"),
 ("Ceiling closes carry a one-day effect, and floor closes a one-day effect plus some later drift.", "Ceiling closes carry a one-day effect, whereas floor closes carry a one-day effect plus some later drift."),
 ("Table 2 decomposes the next-day return as in Equation (5). After a ceiling close the overnight gap", "Table 2 decomposes the next-day return, as in Equation (5). After a ceiling close, the overnight gap"),
 ("The effect sits in the opening auction", "The effect occurs in the opening auction"),
 ("After a floor close the gap is", "After a floor close, the gap is"),
 ("(*t* = `r f(c16(\"Floor all\",\"gap_mkt\",\"t_twoway\"),1)`) and the intraday return is a weak reversal", "(*t* = `r f(c16(\"Floor all\",\"gap_mkt\",\"t_twoway\"),1)`), and the intraday return is a weak reversal"),
 ("% against `r f(c27(7),2)`% for exact hits", "% compared with `r f(c27(7),2)`% for exact hits"),
 ("rather than to closes below the limit.", "rather than closing below the limit."),
 ("The split is therefore weighted", "Therefore, the split is weighted"),
 ("in each tercile of 60-day average dollar volume", "in each tercile of the 60-day average dollar volume"),
 ("Against same-date controls the ceiling gap is", "Against same-date controls, the ceiling gap is"),
 ("and the floor close-to-close return `r f(c16(\"Floor all\",\"cc1_ctrl\"),2)`%", "and the floor close-to-close return is `r f(c16(\"Floor all\",\"cc1_ctrl\"),2)`%"),
 ("on which the market fell more than 2%", "on which the market fell by more than 2%"),
 ("From that open the ceiling return", "From that open, the ceiling return"),
 ("Inside the band the close-to-close", "Inside the band, the close-to-close"),
 ("At the limit the relation breaks", "At the limit, the relation breaks"),
 ("we repeat the comparison with stocks that also closed there.", "we repeat the comparison with stocks that also closed at their high (low)."),
 ("For floors the gap moves", "For floors, the gap moves"),
 ("on the shape of the close but not on news", "on the shape of the close, but not on news"),
 ("needs intraday prices, which we lack", "requires intraday prices, which we lack"),
 ("Table 4 splits the events at 5 May 2025, when HOSE moved", "Table 4 splits the events on May 5, 2025, when the HOSE moved"),
 ("the post-change sample holds", "the post-change sample accounts for"),
 ("Before the change neither", "Before the change, neither"),
 ("in each of the `r nrow(C29)` quarters", "in each of the `r nw(nrow(C29))` quarters"),
 ("significant at the 5% level in `r sum(abs(C29$floor_gap_t) > 1.96)` of them", "significant at the 5% level in `r nw(sum(abs(C29$floor_gap_t) > 1.96))` of them"),
 ("the split at 5 May 2025 gives the largest difference", "the split at May 5, 2025, gives the largest difference"),
 ("positive at the `r sum(pl$floor_gap_diff > 0 & pl$break_date < \"2025-05-05\")` placebo dates", "positive at the `r nw(sum(pl$floor_gap_diff > 0 & pl$break_date < \"2025-05-05\"))` placebo dates"),
 ("and the split at 5 May 2025 gives `r", "and the split at May 5, 2025, gives `r"),
 ("), so the placebo dates cannot separate", "). Therefore, the placebo dates cannot separate"),
 ("Like the split in Table 4,", "As with the split in Table 4,"),
 # --- acronyms (scripts/check_acronyms.py findings) ---
 ("The minimum detectable effect at 80% power", "The minimum detectable effect (MDE) at 80% power"),
 ("Several characteristics (5-day return, MAX, MIN, move frequency, overnight return)", "Several characteristics (5-day return, largest and smallest daily returns, move frequency, and overnight return)"),
 ("event dates, ISO calendar weeks, or blocks", "event dates, calendar weeks (ISO 8601), or blocks"),
 # --- 4. Discussion ---
 ("on HOSE the continuation", "on the HOSE, the continuation"),
 ("a band change on HOSE, like the ChiNext widening that Qi (2023) studies", "a band change on the HOSE, like the ChiNext widening that Qi (2023) studied"),
 ("follows limit closes on HOSE in 2024 to 2026", "follows limit closes on the HOSE from 2024 to 2026"),
]

def apply(b):
    for old, new in EDITS:
        n = b.count(old)
        assert n == 1, (n, old[:80])
        b = b.replace(old, new)
    return b
